### ISSUE TITLE
Out of memory error on script 1 -- HELP!

### ISSUE THREAD

**Issue by sprakashUTH** [GMELab/RV-EXCALIBER#3]
The first time I ran script 1, it worked fine. Every other time I have tried to run it, even on the same data, I get the following errors:

Generating rare-variant gene matrix for uwbatches2-4 and initializing rare variant burden scores per-gene
Error: Out of memory.  The --memory flag may be helpful.
/work/03437/sprakash/lonestar/apps/RVexcaliber/scripts/shell/sub_generate_RVBurdenMatrix_internal_rvexcaliber.clean.sh: fork: Cannot allocate memory

How do I address this problem?

**Comment by rlali** [comment]
Hi @sprakashUTH, can you please copy the exact command (along with input arguments) that you executed? Additionally, it would be helpful to know the following:

1) the system you are using (e.g. mac os, linux etc...)
2) the size of your input dataset
3) were you running anything else that was memory intensive at the same time?

We can troubleshoot with these items so that the issue can be resolved on your end.

Thanks,
Ricky

**Comment by rlali** [comment]
Thank you for the information.

Please try reducing the `job_interval` argument from `10` to `8` and monitor whether the memory consumption reduces (using `top` or `htop`). This input argument will set how many genes are being run in parallel to generate the rare variant burden matrix, so running fewer in parallel might fix the issue.

**Comment by sprakashUTH** [comment]
Reducing to 8 did not fix it, but reducing to 2 did fix the problem and the script completed successfully. I'm still not sure why the script worked originally at 10 and then never again with the same dataset. I'm running on a cluster with more than 100 Gb of memory and the dataset I'm using now is even smaller than the one that worked in the first place.

**Comment by rlali** [comment]
It is returning the error at the stage where the RVBurdenMatrix is to be generated for your internal dataset (i.e. at the `sub_generate_RVBurdenMatrix_internal_rvexcaliber.clean.sh` script?

To be clear, the Rscript called (i.e. `get_Varlist_rvexcaliber.R`) is working, but using too much memory?

It could be stale swap memory that is preventing the `sub_generate_RVBurdenMatrix_internal_rvexcaliber.clean.sh`  from completing properly and producing the full matrix.

It is more odd that this worked without issue the first time around making its something to do with the new dataset, since the first (larger) dataset worked fine.

I would suggest the following troubleshooting steps for now (if you haven't tried already):
1) Use a different subset of this new data (perhaps a different chromosome)
2) Try deleting all files (even if they are empty) returned from this script and re-run
3) If 1 or 2 doesn't work, try on a snippet of the data so we can see if the error still returns on very small file sizes
4) Please re-run on the old dataset that did work - does the error still come up?

The following would also be useful:
1) First few lines of the `.bim` plink file
2) First few lines of the variant list file that generates from the `get_Varlist_rvexcaliber.R` script (i.e. the `variant_list` file)

Thank you.
