### ISSUE TITLE
Error: Incorrect number of inputs

### ISSUE THREAD

**Issue by nikimourtzi** [GMELab/RV-EXCALIBER#6]
I am trying to run get_RVBurdenMatrix_internal_rvexcaliber.clean.sh and I have an error "incorrect number of inputs". 

Do you know why? I have specified all 9 inputs in the script

**Comment by rlali** [comment]
Hi @nikimourtzi. My apologies for the late reply. If this issue was not yet resolved, would you please provide the input arguments you've provided to ``get_RVBurdenMatrix_internal_rvexcaliber.clean.sh``?

If 9 space-delimited arguments are supplied to the shell script, then this error should not pop up.
